package com.app.turtlemint.utils

object UIConstants {
    const val ISSUE_ITEM_CLICK_EVENT = "ISSUE_ITEM_CLICK_EVENT"
    const val DESCRIPTION_SEE_MORE_CLICK_EVENT = "DESCRIPTION_SEE_MORE_CLICK_EVENT"
    const val DESCRIPTION_SEE_LESS_CLICK_EVENT = "DESCRIPTION_SEE_LESS_CLICK_EVENT"

    const val COMMENT_URL = "COMMENT_URL"
    const val TITLE = "TITLE"
    const val DESCRIPTION = "DESCRIPTION"
    const val ISSUE_NUMBER = "ISSUE_NUMBER"
}
